### ISSUE TITLE
!seen <nick> it reply twice

### ISSUE THREAD

**Issue by kcabmaskph** [florian-sander/gseen.mod#13]
**if you use !seen nick it reply twice**

<kcaBmask> !seen player36
09:49:57 PM <Lamestb0t> kcaBmask, player36 (bake@4.us) was last seen parting #test 19 seconds ago (02.12. 13:49), after spending 2 minutes there.
09:49:59 PM <Lamestb0t> kcaBmask, player36 (bake@4.us) was last seen parting #test 19 seconds ago (02.12. 13:49), after spending 2 minutes there.

**but if you use wild card the output is ok** 

<Lamestb0t> kcaBmask, I found one match to your query: player36. player36 (bake@4.us) was last seen parting #test 19 minutes ago (02.12. 13:49), after spending 2 minutes there.

running Eggdrop 1.8.4 using gseen mod 1.1.2

**Comment by florian-sander** [comment]
It's been way to long since I last worked with gseen, so I'm afraid can't be of much help. But here are some pointers which might serve as inspiration for tracking the issue down - or lead you astray, who knows. :)

- It might be that the seen command is somehow double-bound. You could look for reasons why a binding might match the same command.
- Maybe the !seen command and ai seen are triggering simultaneously? Try disabling ai-seen and see if that helps. If yes, you can work from there.

Good luck! If you find out what's going on, please update this issue.

**Comment by kcabmaskph** [comment]
I just did disabling the ai seen.

set ai-seen-binds {
  ""
}

rehash the bot but still give me double output. I did restart and it seems working

Thank you for this mod. This is still the best seen I've ever used.
